[package]
name = "movie-recommender-ai"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
polars = { version = "0.29.0", features = ["lazy", "pivot"]}